#!/bin/bash

# Create or open the SSH configuration file
cat <<EOL >> ~/.ssh/config
Host your_server_alias
    HostName 8.8.8.8
    User ubuntu
    IdentityFile ~/.ssh/school
    PasswordAuthentication no
EOL

